"OZSYNTAX - new verbs and buzzwords for THE SILVER SHOES.
All engine verbs live in zil/zork1/gsyntax.zil; these are additions only."

<BUZZ TOGETHER THREE TIMES PLEASE MY DEAR>

"Chopping. CUT exists only with a WITH clause; CHOP is the game's word."
<SYNTAX CHOP OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-CHOP>
<SYNTAX CHOP = V-CHOP>
<SYNTAX CUT OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-CHOP>
<SYNONYM CHOP HACK HEW FELL>

"Oiling. LUBRICATE OBJECT WITH OBJECT exists; add the bare form."
<SYNTAX LUBRICATE OBJECT = V-OIL>

"Sweeping and household verbs."
<SYNTAX SWEEP OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-SWEEP>
<SYNTAX SWEEP = V-SWEEP>
<SYNONYM SWEEP MOP SCRUB>

"The Lion's verb."
<SYNTAX ROAR = V-ROAR>
<SYNTAX ROAR AT OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-ROAR>
<SYNONYM ROAR GROWL BELLOW>

"The slap that recruits a Lion."
<SYNTAX SLAP OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-SLAP>
<SYNONYM SLAP SMACK SWAT SPANK>

"Bare-handed ATTACK/KILL (the engine only defines the WITH forms
outside Zork II)."
<SYNTAX ATTACK OBJECT (FIND ACTORBIT) (ON-GROUND IN-ROOM) = V-ATTACK>
<SYNTAX KILL OBJECT (FIND ACTORBIT) (ON-GROUND IN-ROOM) = V-ATTACK>

"Riding the Lion."
<SYNTAX RIDE OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-RIDE>
<SYNONYM RIDE MOUNT STRADDLE>

"The Woodman's craft."
<SYNTAX BUILD OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-BUILD>
<SYNTAX BUILD = V-BUILD>
<SYNONYM BUILD CONSTRUCT ASSEMBLE>

"STUFF is an engine synonym of PUT; give PUT a bare-object pattern so
STUFF SCARECROW parses, plus a WITH form."
<SYNTAX PUT OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-STUFF>
<SYNTAX PUT OBJECT WITH OBJECT = V-STUFF>

"Balloon work."
<SYNTAX SEW = V-SEW>
<SYNTAX SEW OBJECT = V-SEW>
<SYNONYM SEW STITCH>

"Affection."
<SYNTAX HUG OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-HUG>
<SYNONYM HUG EMBRACE CUDDLE>

"The heel-knock. KNOCK AT/ON exist; add the bare-object form."
<SYNTAX KNOCK OBJECT = V-KNOCK-HEELS>
<SYNTAX CLICK OBJECT = V-KNOCK-HEELS>
<SYNONYM CLICK CLACK TAP>

"The Golden Cap."
<SYNTAX SUMMON OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-SUMMON>
<SYNTAX SUMMON = V-SUMMON>
<SYNONYM SUMMON CALL INVOKE>
<SYNTAX FLY = V-FLY>
<SYNTAX FLY TO OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-FLY>
<SYNTAX FLY OVER OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-FLY>
<SYNTAX FLY OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-FLY>

"The charm words, sayable bare (like PLUGH) or via SAY."
<SYNTAX EPPE = V-EPPE>
<SYNONYM EPPE PEPPE KAKKE>
<SYNTAX HILLO = V-HILLO>
<SYNONYM HILLO HOLLO>
<SYNTAX ZIZZY = V-ZIZZY>
<SYNONYM ZIZZY ZUZZY ZIK>
<SYNTAX SAY OBJECT = V-SAY-OBJ>

"Going home."
<SYNTAX KANSAS = V-KANSAS>

"Promises and pleas."
<SYNTAX PROMISE = V-PROMISE>
<SYNTAX HELP = V-HELP>
<SYNTAX HELP OBJECT = V-HELP>

"Sleep advances designated days; the engine has no SLEEP verb."
<SYNTAX SLEEP = V-SLEEP>
<SYNONYM SLEEP DOZE SLUMBER>

"Scene-battle verbs."
<SYNTAX LIE DOWN = V-LIE-DOWN>
<SYNTAX LIE = V-LIE-DOWN>
<SYNTAX SCARE OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-SCARE>
<SYNONYM SCARE FRIGHTEN SHOO>
<SYNTAX SCATTER OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-SCATTER>
<SYNONYM SCATTER SPREAD STREW>
<SYNTAX COVER OBJECT WITH OBJECT = V-COVER>
<SYNTAX COVER OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-COVER>

"Tenderness and laundry."
<SYNTAX WIPE OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-WIPE>
<SYNTAX DRY OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-WIPE>
<SYNONYM WIPE DAB>

"Rescues. SAVE keeps its bare save-game form; SAVE OBJECT is a plea."
<SYNTAX STOP OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-STOP>
<SYNTAX SAVE OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-RESCUE>

"The mouse whistle."
<SYNTAX BLOW OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-BLOW-OBJ>

"Messages to a Wizard."
<SYNTAX SEND OBJECT = V-SEND-MSG>
<SYNTAX SEND OBJECT TO OBJECT = V-SEND-MSG>
<SYNTAX THREATEN OBJECT = V-THREATEN>

"ASK X FOR Y."
<SYNTAX TELL OBJECT FOR OBJECT = V-ASK-FOR>

"OIL as its own verb word (it is not an adjective or noun anywhere)."
<SYNTAX OIL OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-OIL>
<SYNTAX OIL = V-OIL>
<SYNTAX OIL OBJECT WITH OBJECT = V-OIL>

"Bare LAUNCH and CROSS for the river."
<SYNTAX LAUNCH = V-LAUNCH-BARE>
<SYNTAX CROSS = V-CROSS-BARE>

"The bucket. THROW/POUR must work whether or not the water is held:
the engine's own forms require (HELD CARRIED HAVE), which loses the
game's crown puzzle to a parser technicality."
<SYNTAX THROW OBJECT (ON-GROUND IN-ROOM HELD CARRIED)
	AT OBJECT (ON-GROUND IN-ROOM) = V-SPLASH>
<SYNTAX THROW OBJECT (ON-GROUND IN-ROOM HELD CARRIED)
	ON OBJECT (ON-GROUND IN-ROOM) = V-SPLASH>
<SYNTAX THROW OBJECT (ON-GROUND IN-ROOM HELD CARRIED)
	OVER OBJECT (ON-GROUND IN-ROOM) = V-SPLASH>
<SYNTAX POUR OBJECT (ON-GROUND IN-ROOM HELD CARRIED)
	ON OBJECT (ON-GROUND IN-ROOM) = V-SPLASH>
<SYNTAX POUR OBJECT (ON-GROUND IN-ROOM HELD CARRIED)
	OVER OBJECT (ON-GROUND IN-ROOM) = V-SPLASH>
<SYNTAX POUR OBJECT (ON-GROUND IN-ROOM HELD CARRIED)
	AT OBJECT (ON-GROUND IN-ROOM) = V-SPLASH>
<SYNTAX SPLASH OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-SPLASH>
<SYNTAX SPLASH OBJECT (ON-GROUND IN-ROOM HELD CARRIED)
	WITH OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-SPLASH>
<SYNONYM SPLASH DOUSE DRENCH SOAK>
<SYNTAX EMPTY OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-SPLASH>
<SYNTAX EMPTY OBJECT (ON-GROUND IN-ROOM HELD CARRIED)
	ON OBJECT (ON-GROUND IN-ROOM) = V-SPLASH>

"Going home: the shoes' own command, in every phrasing that matters.
KANSAS/HOME work bare; SAY KANSAS and WALK TO KANSAS route to V-KANSAS
via the KANSAS-W word object."
<SYNTAX TAKE OBJECT (ON-GROUND IN-ROOM CARRIED HELD) TO OBJECT = V-CARRY-TO>

"Bare HOME / KANSAS as commands (magic-word style, like PLUGH)."
<SYNTAX HOME = V-KANSAS>
<SYNONYM HOME KANSAS>

"Choosing to stay in Oz (the alternate ending at Glinda's)."
<SYNTAX STAY OBJECT = V-STAY>
<SYNONYM STAY REMAIN>
