"OZSYNTAX - new verbs and buzzwords for THE SILVER SHOES.
All engine verbs live in zil/zork1/gsyntax.zil; these are additions only."

<BUZZ TOGETHER THREE TIMES PLEASE MY DEAR>

"Chopping. CUT exists only with a WITH clause; CHOP is the game's word."
<SYNTAX CHOP OBJECT = V-CHOP>
<SYNTAX CHOP = V-CHOP>
<SYNTAX CUT OBJECT = V-CHOP>
<SYNONYM CHOP HACK HEW FELL>

"Oiling. LUBRICATE OBJECT WITH OBJECT exists; add the bare form."
<SYNTAX LUBRICATE OBJECT = V-OIL>

"Sweeping and household verbs."
<SYNTAX SWEEP OBJECT = V-SWEEP>
<SYNTAX SWEEP = V-SWEEP>
<SYNONYM SWEEP MOP SCRUB>

"The Lion's verb."
<SYNTAX ROAR = V-ROAR>
<SYNTAX ROAR AT OBJECT = V-ROAR>
<SYNONYM ROAR GROWL BELLOW>

"The slap that recruits a Lion."
<SYNTAX SLAP OBJECT = V-SLAP>
<SYNONYM SLAP SMACK SWAT SPANK>

"Bare-handed ATTACK/KILL (the engine only defines the WITH forms
outside Zork II)."
<SYNTAX ATTACK OBJECT (FIND ACTORBIT) (ON-GROUND IN-ROOM) = V-ATTACK>
<SYNTAX KILL OBJECT (FIND ACTORBIT) (ON-GROUND IN-ROOM) = V-ATTACK>

"Riding the Lion."
<SYNTAX RIDE OBJECT = V-RIDE>
<SYNONYM RIDE MOUNT STRADDLE>

"The Woodman's craft."
<SYNTAX BUILD OBJECT = V-BUILD>
<SYNONYM BUILD CONSTRUCT ASSEMBLE>

"STUFF is an engine synonym of PUT; give PUT a bare-object pattern so
STUFF SCARECROW parses, plus a WITH form."
<SYNTAX PUT OBJECT = V-STUFF>
<SYNTAX PUT OBJECT WITH OBJECT = V-STUFF>

"Balloon work."
<SYNTAX SEW = V-SEW>
<SYNTAX SEW OBJECT = V-SEW>
<SYNONYM SEW STITCH>

"Affection."
<SYNTAX HUG OBJECT = V-HUG>
<SYNONYM HUG EMBRACE CUDDLE>

"The heel-knock. KNOCK AT/ON exist; add the bare-object form."
<SYNTAX KNOCK OBJECT = V-KNOCK-HEELS>
<SYNTAX CLICK OBJECT = V-KNOCK-HEELS>
<SYNONYM CLICK CLACK TAP>

"The Golden Cap."
<SYNTAX SUMMON OBJECT = V-SUMMON>
<SYNTAX SUMMON = V-SUMMON>
<SYNONYM SUMMON CALL INVOKE>
<SYNTAX FLY = V-FLY>
<SYNTAX FLY TO OBJECT = V-FLY>
<SYNTAX FLY OVER OBJECT = V-FLY>
<SYNTAX FLY OBJECT = V-FLY>

"The charm words, sayable bare (like PLUGH) or via SAY."
<SYNTAX EPPE = V-EPPE>
<SYNONYM EPPE PEPPE KAKKE>
<SYNTAX HILLO = V-HILLO>
<SYNONYM HILLO HOLLO>
<SYNTAX ZIZZY = V-ZIZZY>
<SYNONYM ZIZZY ZUZZY ZIK>
<SYNTAX SAY OBJECT = V-SAY-OBJ>

"Going home."
<SYNTAX KANSAS = V-KANSAS>

"Promises and pleas."
<SYNTAX PROMISE = V-PROMISE>
<SYNTAX HELP = V-HELP>
<SYNTAX HELP OBJECT = V-HELP>

"Sleep advances designated days; the engine has no SLEEP verb."
<SYNTAX SLEEP = V-SLEEP>
<SYNONYM SLEEP DOZE SLUMBER>

"Scene-battle verbs."
<SYNTAX LIE DOWN = V-LIE-DOWN>
<SYNTAX LIE = V-LIE-DOWN>
<SYNTAX SCARE OBJECT = V-SCARE>
<SYNONYM SCARE FRIGHTEN SHOO>
<SYNTAX SCATTER OBJECT = V-SCATTER>
<SYNONYM SCATTER SPREAD STREW>
<SYNTAX COVER OBJECT WITH OBJECT = V-COVER>
<SYNTAX COVER OBJECT = V-COVER>

"Tenderness and laundry."
<SYNTAX WIPE OBJECT = V-WIPE>
<SYNTAX DRY OBJECT = V-WIPE>
<SYNONYM WIPE DAB>

"Rescues. SAVE keeps its bare save-game form; SAVE OBJECT is a plea."
<SYNTAX STOP OBJECT = V-STOP>
<SYNTAX SAVE OBJECT = V-RESCUE>

"The mouse whistle."
<SYNTAX BLOW OBJECT = V-BLOW-OBJ>

"Messages to a Wizard."
<SYNTAX SEND OBJECT = V-SEND-MSG>
<SYNTAX SEND OBJECT TO OBJECT = V-SEND-MSG>
<SYNTAX THREATEN OBJECT = V-THREATEN>

"ASK X FOR Y."
<SYNTAX TELL OBJECT FOR OBJECT = V-ASK-FOR>
